spring.application.name=demo
# Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Senaka123.

# Hibernate / JPA Ayarları (Tabloları otomatik yönetmek için)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081
# Mail Ayarları
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Kendi Gmail adresini yaz
spring.mail.username=helpdesk1052026@gmail.com
# Az önce Google'dan kopyaladığın 16 haneli şifreyi (boşluksuz) buraya yapıştır
spring.mail.password=mjusikdkuokatwgy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
